export default {
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: '60',
      brand: 'Nike',
      rating: 4.2,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: '45',
      brand: 'Nike',
      rating: 4.4,
      numReviews: 12,
      countInStock: 8,
    },
    {
      _id: '3',
      name: 'Best pants',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: '70',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 18,
      countInStock: 11,
    },
    {
      _id: '4',
      name: 'Nice pants',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: '70',
      brand: 'Nike',
      rating: 4.2,
      numReviews: 5,
      countInStock: 9,
    },
  ],
};
